### ISSUE TITLE
[Bug] Klippa Integration Causes App Crashes in Android When Camera is Used by Other Plugins

### ISSUE THREAD

**Issue by aboobacker-sid** [klippa-app/flutter-klippa-identity-verification-sdk#33]
**Steps to Reproduce:**
- Open Klippa session and start the document scanning with camera
- Complete the Klippa journey or cancel and return to app screen
- Open camera from elsewhere in the app using [image_picker plugin](https://pub.dev/packages/image_picker)
- Tap the capture button, app crashes instantly

Note : 
- If we do not start any Klippa sessions, other plugins are able to access the camera freely without any issues.
- Issue occurs only in Android

**Expected Behavior:**
- Other plugins should be able to access camera freely.

**Actual Behaviour:**
- `onActivityResult(KlippaIdentityVerificationSdkPlugin.kt:176)` from Klippa SDK is being triggered by camera capture from other plugins even after closing the Klippa session. This causes the app to crash.

**Screenshots/Videos:**
- [Screen capture of the entire journey leading to crash](https://github.com/user-attachments/assets/a82326cc-d523-4a98-8d42-3fb94384ae70) 

**Error Messages:**
- [logs.](https://github.com/user-attachments/files/18109055/campus_connect_logs.txt)

**Environment:**
- Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.26100.2314], locale en-US)
- klippa_identity_verification_sdk: 0.2.10
- image_picker: ^1.1.2

**Comment by RobinFarmer** [comment]
Hi @aboobacker-sid 

Thanks for reporting this, in version [`0.2.10`](https://github.com/klippa-app/flutter-klippa-identity-verification-sdk/releases/tag/0.2.10) we introduced a change for handling the [result](https://github.com/klippa-app/flutter-klippa-identity-verification-sdk/blob/master/android/src/main/kotlin/com/klippa/identity_verification/klippa_identity_verification_sdk/KlippaIdentityVerificationSdkPlugin.kt#L161) could you confirm it still happens using this version?

**Comment by aboobacker-sid** [comment]
@RobinFarmer Thnaks. The issue seems to be resolved with the latest update.
